### ISSUE TITLE
Feature: don't allow players to play each other twice

### ISSUE THREAD

**Issue by nateberkopec** [aflock/swiss#5]
There was a pretty obvious instance last night when playing a casual draft tournament where two players got matched together two rounds in a row. Although I can't find it any [DCI-official documentation](http://www.wizards.com/dci/downloads/Swiss_Pairings.pdf), a no-same-pairing option sounds like a good idea. IMO, the Player should probably just append each new player to some array like #already_played and check that while pairing.

The problem is - what do you do when you have a pairing that has already occurred? Any other pairing that is _not_ pairing players together with the same match point total is generally unfair to the lower-ranked player. See last night's example:

Player A: 1 MP
Player B: 1 MP
Players C, D, E, F: 1MP.

The original pairing was A,B; C,D; E,F. This was a fair pairing, since players with the same MP total were paired together. However, A and B had already played. Our new pairing was something like A,C; B,D; E,F; which means that players C and D are getting a raw deal, because they are lower ranked than players A and B.

So, when you don't allow the same players to play twice, you fix two people's problems (boredom/playing same match twice) and then two more people have problems (fairness). Both scenarios suck, which is why I guess it makes sense to have an option so the user can decide which scenario sucks less.

There are so many different systems of "Swiss" tournament pairing, that it seems like options/different modes might become a bigger feature later.

**Comment by emmettbutler** [comment]
For what it's worth, the latter situation (rank mismatches rather than duplicate pairings) is the way it's done at every other draft event I've been to (Montasy, 20 Sided, MAGfest). I think it's generally preferable to play a new opponent regardless of match points
